# Generated by Django 6.0.2 on 2026-02-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilreport',
            name='predicted_fertilizer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
