# Generated by Django 6.0.2 on 2026-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_soilreport_predicted_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilreport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
